### ISSUE TITLE
[Documentation] enable Github wiki for repository

### ISSUE THREAD

**Issue by MildlyInterested** [KAT-Advanced-Medical/KAM#109]
As title says please enable the github wiki for this repository and allow specific users/logged in users to edit it. 

In my opinion that would be the best and easiest way to create up to date and centralized documentation of the mountain of features that KAT brings into Arma 3.

**Comment by YetheSamartaka** [comment]
👍🏻

**Comment by YetheSamartaka** [comment]
Done.
