### ISSUE TITLE
Hyperextending head ignores spO2 loss due to no heart rate

### ISSUE THREAD

**Issue by Filip-88** [KAT-Advanced-Medical/KAM#154]
**Description:**
- When hyperextending head the spO2 levels will rise even if patient has no heart rate (and the option for spO2 loss during no heart rate is active)

**Steps to reproduce:**
- have the option for spO2 loss during no heart rate active
- have a patient go uncon with no heart rate.
- use hyperextending head.
- spO2 will now rise instead of going down slower.

**Where did the issue occur?**
- Dedicated / Editor (Singleplayer) / Editor (Multiplayer)

**Placed Modules:**
- None

**Suggested change / fix**
in [fnc_handleBreathing.sqf](https://github.com/Tomcat-SG/KAM/blob/dev-Tomcat/addons/breathing/functions/fnc_handleBreathing.sqf), at line 87 change the handling of airway to this instead:
```sqf
if !(_airway) exitWith {
    _output = -0.3 * _multiplierNegative;
    
    if (_overstretch && _unit getVariable [QEGVAR(airway,obstruction), false]) then {
        
        if ((_heartRate < 20) && {GVAR(SpO2_perfusion)}) then {
            _output = -0.2 * GVAR(SpO2_PerfusionMultiplier);
        }
        else {
            _output = 0.15 * _multiplierPositive;
        };
    };

    _finalOutput = _status + _output;

    if (_finalOutput > 100) then {
        _finalOutput = 100;
    };

    if (_finalOutput < 1) then {
        _finalOutput = 1;
    };

    _unit setVariable ["KAT_medical_airwayStatus", _finalOutput, true];
};
```

**Comment by MiszczuZPolski** [comment]
@YetheSamartaka can you look into it?

**Comment by YetheSamartaka** [comment]
Fixed.
