### ISSUE TITLE
Obstruction and occlusion interversion

### ISSUE THREAD

**Issue by ArwynFr** [KAT-Advanced-Medical/KAM#203]
Definitions from the dictionary:
* Occlusion is the blockage or closing of a blood vessel or hollow organ.
* Obstruction happens when something blocks a road, passage, entrance, etc.

Occlusion is what happens when the airway collapse, and should be fixed by overstretching the head or inserting a guedel tube.
Obstruction is what happens when the patient vomits, and should be fixed by head turning or using an accuvac.

The terms are used inversely in the mod.

Mnemonic:
* obstruction = obstacle
* occlusion = closed

**Comment by MiszczuZPolski** [comment]
We had discussion about this "issue" many times on discord - and it has always appeared that these terms are used interchangeably or differ from country to country (UK,US,AUS) so i dont see reason to change it.
I will close this issue but you can start discussion about it on discord, maybe we will work out better solution.
