### ISSUE TITLE
Request: Default Bloodtype for ACE Blood items

### ISSUE THREAD

**Issue by Th3Jock3R** [KAT-Advanced-Medical/KAM#222]
Hallo,

first thank you for continue the development of this great mod... We realy appreciate it!

Second, to my request:
It would be very nice if there is a setting option in the CBA settings for the KAT blood groups, as what the normal ACE blood items without blood group are treated.

My suggestion for this would be the setting options:

- **0**: that means it is compatible with all Bloodtypes
- **random**: That means when creating the transfusion, it will be decided internally which blood type it is. (good for survival missions, where unidentified blood can be found)
- **Incidentally with Incompatible**: Here, there would be a risk for AB (& AB+) to get an incompatible blood unit because either donors blood unit is a rare blood group which cannot be mapped within the AB rhesus factor system or the unit is simply spoiled.
- **Incompatible**: are always incompatible, RP technically corrupted or contaminated in end time scenarios like Exile or similar.

Thank you for you great work and wish you all a nice Christmas time!

**Comment by MiszczuZPolski** [comment]
#29 please write it here
