### ISSUE TITLE
Resource title ace_interact_menu_menuBackground not found

### ISSUE THREAD

**Issue by NZF-JDWang** [KAT-Advanced-Medical/KAM#230]
![image](https://user-images.githubusercontent.com/31868402/211175337-a80e256a-533e-436e-ac36-444a2c49f8b5.png)

the Resource title should be 

ace_interact_menu_menuBackground

but there's an A where there should be an E - simple typing error

**Comment by MiszczuZPolski** [comment]
Its already fixed on github, wait for update
