### ISSUE TITLE
fnc_treatmentAdvanced_FlushLocal.sqf has wrong documentation

### ISSUE THREAD

**Issue by enricomfg** [KAT-Advanced-Medical/KAM#260]

**Comment by MiszczuZPolski** [comment]
What do you mean?

**Comment by enricomfg** [comment]
I meant the comment at the beggining of the file, it described what NaloxoneLocal does, not FlushLocal

**Comment by MiszczuZPolski** [comment]
Its called "header" but yeah, i saw what you mean, i will correct it in future

**Comment by MiszczuZPolski** [comment]
Resolved in #261
