### ISSUE TITLE
Painkillers Bug?

### ISSUE THREAD

**Issue by Salzenberger** [KAT-Advanced-Medical/KAM#311]
**Mods:**
```
- CBA_A3
- ace
- KAT
```

**Description:**
- Painkillers dont save in ACE Arsenal Loudout (picked under Category Medical).
- Displayed Painkillers in Arsenal dont show up more than 1  

**Steps to reproduce:**
- Save Painkillers in Uniform, load it - painkillers are not there.
- Pick Painkillers at the Medical Category in the ACE Arsenal.

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal

**Comment by MiszczuZPolski** [comment]
Unless you use restricted arsenal, it should be saved. Be sure you allow painkillers from magazines too (i think it might be hidden)

**Comment by Salzenberger** [comment]
> Unless you use restricted arsenal, it should be saved. Be sure you allow painkillers from magazines too (i think it might be hidden)

Thank you for your Answer. 
I will try it out - they are added but it dont work. But in the ACE Virtual Arsenal the bug with "Displayed Painkillers in Arsenal dont show up more than 1" is still there? I reapaired my mod, load it form Steam and load it local.
