### ISSUE TITLE
CBA event "ace_treatmentStarted" does not fire when kat is loaded

### ISSUE THREAD

**Issue by Tapawingo** [KAT-Advanced-Medical/KAM#338]
**Arma 3 Version:** `2.12` stable
**CBA Version:** `3.15.8` stable
**ACE3 Version:** `3.15.2` stable

**Mods:**
```
- CBA_A3
- ace
- kat
```

**Description:**
- The ace CBA event "ace_treatmentStarted" does not fire when kat is loaded. 
- Other events such as "ace_treatmentSucceded" and "ace_treatmentFailed" does fire. 
- When kat is not loaded "ace_treatmentStarted" event works fine

**Steps to reproduce:**
- Launch Arma 3 with cba, ace and kat loaded
- Open a mission in the editor
- Add cba event in initPlayerLocal
- Start mission in either singleplayer or hosted multiplayer
- Injure player and apply treatment

**Where did the issue occur?**
- Dedicated, Editor (Singleplayer) and Editor (Multiplayer)

**Placed Modules:**
- None

**RPT log file:**
- https://pastebin.com/hBSjMfiL

**Mission file:**
- https://files.catbox.moe/iq3ixh.zip

**Comment by Tapawingo** [comment]
The same mission was tested with only ace and CBA loaded and the event fires correctly

**Comment by MiszczuZPolski** [comment]
Fixed in #339, you can test it yourself by downloading artifact on the bottom of this link
https://github.com/KAT-Advanced-Medical/KAM/actions/runs/5256054965?pr=339

**Comment by Tapawingo** [comment]
Can confirm it now works on my end as well 👍.
