### ISSUE TITLE
kat_stretcher does not support extended eventhandlers

### ISSUE THREAD

**Issue by MildlyInterested** [KAT-Advanced-Medical/KAM#377]
**Arma 3 Version:** `2.12.150806` (latest profiling)
**CBA Version:** `3.15.8` (latest steam)
**ACE3 Version:** `3.15.2` (latest steam)
**KAT Version:** `2.10.4` (one year old, still present in latest steam)

**Mods:**
```
- CBA_A3
- ace
- some more but not relevant
```

**Description:**
- KAT Stretcher does not support XEHs, not a big deal but would be nice to see fixed.
- Describes how to inherit to support XEHs https://github.com/CBATeam/CBA_A3/wiki/Extended-Event-Handlers-(new)#compatibility-without-dependance

**Steps to reproduce:**
1. Launch game with KAT loaded
2. open rpt file and observer error

**Where did the issue occur?**
- Dedicated&Clientside, all versions

**RPT log file:**
[arma3profiling_x64_2023-07-25_12-10-57.txt](https://github.com/KAT-Advanced-Medical/KAM/files/12165195/arma3profiling_x64_2023-07-25_12-10-57.txt)

**Comment by AtrixZockt** [comment]
The stretcher will get a complete rework soon.

**Comment by cruiser1092** [comment]
Is the stretcher possible to carry with two people as in the main photo of the mod?
