### ISSUE TITLE
Conflict with  Animated Recoil coefficient changer.

### ISSUE THREAD

**Issue by Holgerhollebolle** [KAT-Advanced-Medical/KAM#404]
I get this Error with KAT conflicting maybe with the Mod: Animated Recoil coefficient changer.
![Screenshot_230829_arma3profiling_x64_1591](https://github.com/KAT-Advanced-Medical/KAM/assets/10847197/6aec19c4-876b-4c2e-ad2e-9d51ea3bda0a)

here is the link to the possibly confilcting mod:
https://steamcommunity.com/sharedfiles/filedetails/?id=2623341670&searchtext=+Animated+Recoil+coefficient+changer.

**Comment by MiszczuZPolski** [comment]
Issue is not created according to template, please adjust it
