### ISSUE TITLE
Mod Conflict with Animated Recoil coefficient changer

### ISSUE THREAD

**Issue by Holgerhollebolle** [KAT-Advanced-Medical/KAM#407]
**Description:**
When you run KAT with this Mod it produces an Error. The error is attached as an Image.

https://steamcommunity.com/sharedfiles/filedetails/?id=2623341670&searchtext=+Animated+Recoil+coefficient+changer

**Steps to reproduce:**

The Error pops up after a while playing any mission. It than comes again and again repetetly.

**Where did the issue occur?**
I only tested it playing local in the Editor. But I am sure its an issue also in Multiplayer and dedicated.

[cba_settings.txt](https://github.com/KAT-Advanced-Medical/KAM/files/12472282/cba_settings.txt)
[arma3profiling_x64_2023-08-30_07-55-15.txt](https://github.com/KAT-Advanced-Medical/KAM/files/12472283/arma3profiling_x64_2023-08-30_07-55-15.txt)

**Comment by Apricot-ale** [comment]
Try again with only loads CBA, ACE, KAT and Animated Recoil coefficient changer and turn on check -debug on parameters.
then send rpt log again.

Please note whether you are using the DEV/Stable version of KAT.

**Comment by Apricot-ale** [comment]
Well, maybe this is an error only for KAT and ACE, regardless of that mod.
How to reproduce:
1. Load only CBA, ACE, KAT (stable)
2. Play the mission with the player and the AI rifleman in the editor. (Any map)
3. Open ZEUS (from ACE ZEUS interaction or ZEUS module)
4. Use ACE FULL HEAL module for AI.
I get a similar error.

**Comment by Apricot-ale** [comment]
```11:56:17 Error in expression <ctor;
ace_advanced_fatigue_swayFactor = kat_pharma_originalSwayFactor;

} else {>
11:56:17   Error position: <kat_pharma_originalSwayFactor;

} else {>
11:56:17   Error undefined variable in expression：kat_pharma_originalswayfactor
11:56:17 File x\kat\addons\breathing\functions\fnc_fullHealLocal.sqf..., line 155
11:56:17  ➥ Context: 	[Main] L46 (/z/ace/addons/zeus/functions/fnc_moduleHeal.sqf)
	[] L48 (/z/ace/addons/zeus/functions/fnc_moduleHeal.sqf)
	[] L34 (/x/cba/addons/events/fnc_targetEvent.sqf)
	[] L35 (/x/cba/addons/events/fnc_targetEvent.sqf)
	[] L35 (/x/cba/addons/events/fnc_targetEvent.sqf)
	[] L35 (/x/cba/addons/events/fnc_targetEvent.sqf)
	[] L150 (x\kat\addons\breathing\functions\fnc_fullHealLocal.sqf)
	[] L155 (x\kat\addons\breathing\functions\fnc_fullHealLocal.sqf)
```

**Comment by Apricot-ale** [comment]
This not fixed at DEV version too (not the same line but same error)
```12:02:59 Error in expression <ctor;
ace_advanced_fatigue_swayFactor = kat_pharma_originalSwayFactor;

} else {>
12:02:59   Error position: <kat_pharma_originalSwayFactor;

} else {>
12:02:59   Error undefined variable in expression：kat_pharma_originalswayfactor
12:02:59 File x\kat\addons\misc\functions\fnc_fullHealLocal.sqf..., line 167
12:02:59  ➥ Context: 	[Main] L46 (/z/ace/addons/zeus/functions/fnc_moduleHeal.sqf)
	[] L48 (/z/ace/addons/zeus/functions/fnc_moduleHeal.sqf)
	[] L34 (/x/cba/addons/events/fnc_targetEvent.sqf)
	[] L35 (/x/cba/addons/events/fnc_targetEvent.sqf)
	[] L35 (/x/cba/addons/events/fnc_targetEvent.sqf)
	[] L35 (/x/cba/addons/events/fnc_targetEvent.sqf)
	[] L162 (x\kat\addons\misc\functions\fnc_fullHealLocal.sqf)
	[] L167 (x\kat\addons\misc\functions\fnc_fullHealLocal.sqf)
```

**Comment by MiszczuZPolski** [comment]
Changing sway is currently disabled, will be reworked with appropriate ace function.
