### ISSUE TITLE
Medical and Ace interaction

### ISSUE THREAD

**Issue by Markie4** [KAT-Advanced-Medical/KAM#424]
Medical menu:
Some things are in russian for ex. gave guedel tube and it says in russian what i just did
doesnt show injury type
everything is blue, no injury colours
kicks you out the menu after every application of ___ 
sometimes bandaging/tourniquet is INCREDIBLY confusing

Also talked to ACE people and they said they saw similar issue with ace interaction being fucked due to KAT

**Comment by MiszczuZPolski** [comment]
Edit your bug report following template and add rpt
