### ISSUE TITLE
Missing item: Pavulonik

### ISSUE THREAD

**Issue by zbysiek** [KAT-Advanced-Medical/KAM#439]
**Description:**
Pavulon (Pankuronium) is missing from the medical items, literally unplayable.

https://nonsa-pl.translate.goog/wiki/Pavulon?_x_tr_sl=pl&_x_tr_tl=en&_x_tr_hl=pl&_x_tr_pto=wapp

https://youtu.be/EpeXYWSnKW0

**Comment by MiszczuZPolski** [comment]
Not funny
