### ISSUE TITLE
Mortars do not work

### ISSUE THREAD

**Issue by diaverso** [KAT-Advanced-Medical/KAM#464]
**Modlist and KAT Version will be auto extracted from your attached RPT**
ACE
CBA
KAT - Advanced Medical

**Description:**
When you put a mortar in it does not work

**Steps to reproduce:**
When you place a zeus mortar or arsenal and try to fire or reload it, it does not work and an error is displayed.
https://i.imgur.com/4uPqZeA.jpeg

**Where did the issue occur?**
- Editor (Singleplayer) 

**Additional information:**
class ACE_mortar_82mm: mortar_82mm
{
magazines[]=
{
"KAT_1Rnd_82mm_Mo_Type0",
"KAT_1Rnd_82mm_Mo_TypeCS"
};
};

Can you fix that line 825 ?
magazines[]+=
should be to fix the mortar.

made this fork which I think would fix it.
https://github.com/KAT-Advanced-Medical/KAM/pull/465

**Comment by MissHeda** [comment]
Can't replicate, check your ACE version, this is not a problem caused by our mod!

**Comment by diaverso** [comment]
I have the latest versions of the workshop
record a video, so that it can be seen
https://www.youtube.com/watch?v=2YGecDnpC8Y

**Comment by diaverso** [comment]
In the workshop comments @YetheSamartaka He says he knows the problem and is working to fix it.

https://i.imgur.com/JzfYhCZ.png

**Comment by MissHeda** [comment]
still can't replicate, check addon settings.
