### ISSUE TITLE
if !local _unit check missing

### ISSUE THREAD

**Issue by MildlyInterested** [KAT-Advanced-Medical/KAM#52]
**Description:**
<https://forums.bohemia.net/forums/topic/211626-arma-script-profiler/?do=findComment&comment=3387631>

**Steps to reproduce:**
>  Ah so kat_aceBreathing and kat_aceCirculation are initializing the unit, and while doing that sending variables.
That doesn't seem right, the unit is local to the server, it should only be initialized on the server.
If my client initializes its variables, then so does every client. 

**Where did the issue occur?**
- Dedicated

**Placed Modules:**
- None

**Comment by YetheSamartaka** [comment]
Thank you for pointing this out, the situation is being analyzed and the issue fixed hopefully soon.

**Comment by MildlyInterested** [comment]
I think (and hope) this issue can be closed now?
