### ISSUE TITLE
Update the Wiki

### ISSUE THREAD

**Issue by DJ-Rei** [KAT-Advanced-Medical/KAM#528]
**Modlist and KAT Version will be auto extracted from your attached RPT**
Make sure to attach it to this report!
Doesn't Apply
**CBA Settings**

<details>
  <summary>CBA Settings</summary>
Doesn't Apply
  ```sqf
  Paste your settings in here.
  ```  
</details>

**Description:**
- Add a detailed description of the error. This makes it easier for us to fix the issue. If applicable, add screenshots to help explain your problem (simply copy and paste). 
**Wiki has not been updated since April of 2023. There is no class names listed for the new items added in recent updates.**
**Steps to reproduce:**
Add the steps needed to reproduce the issue.
Doesn't Apply
1. _Go to ..._
2. _Click ..._
3. _See ..._

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer / Singleplayer / Editor (Singleplayer) / Editor (Multiplayer) / Virtual Arsenal
GitHub
**Additional information:**
Provide any additional information that will help us solve this issue.

**RPT log file:**
- Attach your RPT log file as a txt file. It can be found in `C:\Users\YOURUSERNAME\AppData\Local\Arma 3` and then add `.txt` to the end of the filename. Detailed instructions to find your RPT files can be found [here](https://community.bistudio.com/wiki/Crash_Files#Arma_3).

**Comment by Apricot-ale** [comment]
I had created and uploaded the class list of KAM on discord in the past.
Then people who could edit the wiki added them, but I haven't uploaded them for a while cuz I don't need that anymore.
It's done entirely on a voluntary basis, and people who feel they need it upload it themselves.
So if you think it should be updated, please create a list of them and post it on the discord or this issue.
