### ISSUE TITLE
Intubation with Occlusion Incorrect Message

### ISSUE THREAD

**Issue by TYKUHN2** [KAT-Advanced-Medical/KAM#54]
**Description:**
- Attempting intubation (with obstruction) when occluded (vomit) notifies the user the airway is clear whilst consuming the item and not intubating.
- This behavior is incorrect, either intubation should still work, or the user should be notified to clear the airway, rather than that the airway is clear.

Both fixes are within [fnc_treatmentAdvanced_airwayLocal](https://github.com/Tomcat-SG/KAM/blob/dev-Tomcat/addons/airway/functions/fnc_treatmentAdvanced_airwayLocal.sqf)

Fix 1: Remove lines 22-26
```
-if (_target getVariable ["KAT_medical_airwayOccluded", false]) exitWith {
-   private _output = localize LSTRING(Airway_NA);
-   [_output, 1.5, _caller] call ace_common_fnc_displayTextStructured;
-   false;
-};
```

Fix 2: Add new localization at line 23 (and in stringtable.xml)
```
-private _output = localize LSTRING(Airway_NA);
+private _output = localize LSTRING(Airway_Need_Clear);
```
Additionally, the intubation item should not be consumed, but I am not familiar enough with the code to produce the snippet.

**Comment by YetheSamartaka** [comment]
Okay, we'll look into it.
