### ISSUE TITLE
ACE/KAM Painkillers config conflict

### ISSUE THREAD

**Issue by AgentDove** [KAT-Advanced-Medical/KAM#546]
**Description:**
Ace recently added their own painkillers, and its uses the config name 'PainKillers' in the Ace Medical Treatment cfg's.
Kat also uses the same config name for its painkillers.

**Steps to reproduce:**
1. Load into Ace virtual arsenal.
2. Add "ace_painkillers" to your inventory
3. Try to use said painkillers on your head.
4.  No option appears.

**Where did the issue occur?**
- Self-Hosted Multiplayer  / Virtual Arsenal

**Additional information:**
ACE_Medical_Treatment_Actions
[Ace Painkillers -  Config](https://github.com/acemod/ACE3/blob/565d64d50ed775dafbbefafe05457577e955712b/addons/medical_treatment/ACE_Medical_Treatment_Actions.hpp#L145)
[KAM Painkillers -  Config](https://github.com/KAT-Advanced-Medical/KAM/blob/e7196ae992eb2e4e2d8135933a9d0e8994d464bf/addons/pharma/ACE_Medical_Treatment_Actions.hpp#L43)
ACE_Medical_Treatment >> Medication
[Ace Painkillers - Config](https://github.com/acemod/ACE3/blob/565d64d50ed775dafbbefafe05457577e955712b/addons/medical_treatment/ACE_Medical_Treatment.hpp#L610C15-L610C26)
[KAM Painkillers - Config](https://github.com/KAT-Advanced-Medical/KAM/blob/e7196ae992eb2e4e2d8135933a9d0e8994d464bf/addons/pharma/ACE_Medical_Treatment.hpp#L175)

The items do not conflict with each other, only the medical configs.

**Comment by Cplhardcore** [comment]
Just a note, if you are running KAM, you should also be running the painkillers as well, as they do more then just remove pain
