### ISSUE TITLE
Multiplayer Scoreboard not countig kills

### ISSUE THREAD

**Issue by Lefrets** [KAT-Advanced-Medical/KAM#71]
**Arma 3 Version:** `2.06` (stable)
**CBA Version:** `v3.15.6.211004` (stable)
**ACE3 Version:** `3.14.0` (stable)

**Mods:**
```
- CBA_A3
- ace
- KAT - Rewrite
```

**Description:**
- Since the last KAT - Rewrite Update (26.09.2021) the Multiplayer Scoreboard (accessed by perssing "p") doesn't count kills anymore. Deaths are still counted as usual, but no matter how someone dies (even with ace unconscious turened off) the kill is not counted. 

**Where did the issue occur?**
- Dedicated / Self-Hosted Multiplayer

**Comment by MiszczuZPolski** [comment]
![20211024224228_1](https://user-images.githubusercontent.com/71414303/138612215-10d54c6a-e56f-45cd-8fe8-9cfab888d922.jpg)
Checked with only cba and ace, looks like not KAT problem

**Comment by Tomcat-SG** [comment]
ACE related problem
