### ISSUE TITLE
Request - Medical Audit Log

### ISSUE THREAD

**Issue by WillBolton45** [KAT-Advanced-Medical/KAM#79]
It would be a somewhat annoyingly useful feature. A log to the servers directory where it records all medical action taken by all players, to other players.

_time_ - Katalam gave Yethe Samartaka morphine
_time_ - Yethe Samartaka went unconscious

Not sure how difficult this would be! But ACE already has this in some sense in the medical menu.

**Comment by RSpeekenbrink** [comment]
The only way of writing this to an external log (not the default server log) is via an extension (dll) which is quite a process. Also requires BattleEye approval etc.

**Comment by MiszczuZPolski** [comment]
So just like RSpeekenbrink said, we can make extension (which i have never tried to do) or make it log into RPT, but  i am not sure if thats really needed in KAM. We would need to add this to every medical action and it would take some time. Especially when we try not to override ace files. I think you can suggest it to ACE team on their github in feature request issue:
https://github.com/acemod/ACE3/issues/3594
